/* Build: bundles the TypeScript source into the two artifacts the repo ships.
   sh-os.js is the drop-in (an IIFE, no dependencies) that the portfolio pages embed and Vercel serves as-is, so it
   is committed. examples/react/app.js is the React example, with React itself left external for the page's import
   map. Run with `npm run build`; `npm test` builds first so the browser test drives a fresh bundle. */
import { build } from 'esbuild';

const banner = `/* SH-OS runtime bundle, generated by \`npm run build\` from src/ (TypeScript). Do not edit this file; edit src/ and rebuild.
   The instrument in one script, no dependencies: a page needs sh-os.css, <div data-shos data-assets="…/assets/"> and this file.
   Source and docs: https://github.com/spence52602/sh-os */`;

await build({
  entryPoints: ['src/embed.ts'], bundle: true, format: 'iife', target: 'es2018', outfile: 'sh-os.js',
  banner: { js: banner }, legalComments: 'none', charset: 'utf8', logLevel: 'info',
});
await build({
  entryPoints: ['examples/react/app.tsx'], bundle: true, format: 'esm', target: 'es2020', outfile: 'examples/react/app.js',
  external: ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime'], jsx: 'automatic', charset: 'utf8', logLevel: 'info',
});
